// Auto-generated by scripts/setup-vendors.ts — do not edit manually.
// Update by running: bun scripts/setup-vendors.ts --cef-only
export const CEF_VERSION = "147.0.9+g2812b73+chromium-147.0.7727.49";
