// Auto-generated by scripts/setup-vendors.ts — do not edit manually.
// Update by running: bun scripts/setup-vendors.ts --cef-only
export const CEF_VERSION = "146.0.10+g8219561+chromium-146.0.7680.179";
