// Auto-generated by scripts/setup-vendors.ts — do not edit manually.
// Update by running: bun scripts/setup-vendors.ts --cef-only
export const CEF_VERSION = "152.0.8+g1ce985c+chromium-152.0.7977.134";
